<a href="https://colab.research.google.com/github/PolianaQueiroz/Master-Research-Lab/blob/main/C%C3%B3pia_de_RNA_Atividade_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Crie um modelo perceptron e aplique para prever os seguintes casos:
1. Caso do AND
2. Caso do OR
3. Caso do XOR

Para cada caso defina sua própria estratégia de inicialização dos pesos. Comente os resultados obtidos em cada caso.

In [ ]:
import numpy as np

# ----------------------------------------------------------------
# PASSO 1: CRIAR O MODELO PERCEPTRON
# ----------------------------------------------------------------
# Vamos criar uma classe que define o Perceptron.
# Ele terá um "learning rate" (taxa de aprendizado) e "epochs" (número de épocas de treino).
# A inicialização dos pesos será feita dentro do método 'fit' (treinar).

class Perceptron:
    def __init__(self, learning_rate=0.1, n_epochs=100):
        self.learning_rate = learning_rate
        self.n_epochs = n_epochs
        self.weights = None  # Pesos (w1, w2)
        self.bias = None     # Viés (b)

    def _step_function(self, z):
        # Esta é a função de ativação degrau (Heaviside)
        # Retorna 1 se z >= 0, e 0 se z < 0
        return np.where(z >= 0, 1, 0)

    def fit(self, X, y):
        """
        Esta é a função de treino.
        Aqui, definimos nossa estratégia de inicialização dos pesos.

        Estratégia de Inicialização:
        Para simplificar e garantir reprodutibilidade, vamos iniciar os pesos e o bias com ZERO.
        """
        n_samples, n_features = X.shape

        # Inicialização dos pesos e bias
        self.weights = np.zeros(n_features)
        self.bias = 0.0

        print(f"Treinando... (Pesos Iniciais: {self.weights}, Bias Inicial: {self.bias})")

        # Loop de treinamento (regra de aprendizado do Perceptron)
        for _ in range(self.n_epochs):
            for idx, x_i in enumerate(X):
                # 1. Calcular a saída líquida (z)
                z = np.dot(x_i, self.weights) + self.bias

                # 2. Aplicar a função de ativação para prever (y_pred)
                y_pred = self._step_function(z)

                # 3. Calcular o erro e atualizar os pesos
                # A mágica do aprendizado está aqui:
                # Se y_pred == y_true (acertou), o erro (y[idx] - y_pred) é 0, e nada muda.
                # Se errou, o erro é 1 ou -1, e os pesos/bias são ajustados.
                update = self.learning_rate * (y[idx] - y_pred)

                self.weights += update * x_i
                self.bias += update

        print(f"Treino concluído. (Pesos Finais: {self.weights}, Bias Final: {self.bias})")

    def predict(self, X):
        """Esta função usa os pesos treinados para prever novos dados."""
        z = np.dot(X, self.weights) + self.bias
        return self._step_function(z)

# ----------------------------------------------------------------
# PASSO 2: DEFINIR OS DADOS DE TREINO
# ----------------------------------------------------------------

# Entradas (X) - Os 4 casos possíveis
# (0,0), (0,1), (1,0), (1,1)
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Saídas desejadas (y) para cada caso
y_and = np.array([0, 0, 0, 1])
y_or = np.array([0, 1, 1, 1])
y_xor = np.array([0, 1, 1, 0])


def run_test(case_name, X, y_true):
    """Função auxiliar para treinar e testar cada caso."""
    print(f"\n--- TESTANDO O CASO: {case_name} ---")

    # 1. Criar uma nova instância do Perceptron
    # (Usamos a mesma inicialização de pesos/bias = 0 para todos os casos)
    perceptron = Perceptron(learning_rate=0.1, n_epochs=100)

    # 2. Treinar o modelo com os dados específicos (X, y_true)
    perceptron.fit(X, y_true)

    # 3. Fazer as previsões com o modelo treinado
    y_pred = perceptron.predict(X)

    # 4. Mostrar os resultados
    print("\nResultados:")
    print("Entrada | Desejado | Previsto | Correto?")
    print("------------------------------------------")

    total_correct = 0
    for i in range(len(X)):
        is_correct = "Sim" if y_true[i] == y_pred[i] else "NÃO"
        if is_correct == "Sim":
            total_correct += 1
        print(f"{X[i]}  |    {y_true[i]}     |     {y_pred[i]}    |   {is_correct}")

    print(f"\nAcurácia: {total_correct / len(X) * 100}%")

    if total_correct == len(X):
        print("Comentário: Sucesso! O Perceptron convergiu e aprendeu a função.")
    else:
        print("Comentário: Falha! O Perceptron não conseguiu aprender esta função.")


# ----------------------------------------------------------------
# PASSO 3: RODAR OS TESTES
# ----------------------------------------------------------------

# Caso 1: AND
run_test("AND", X, y_and)

# Caso 2: OR
run_test("OR", X, y_or)

# Caso 3: XOR
run_test("XOR", X, y_xor)


--- TESTANDO O CASO: AND ---
Treinando... (Pesos Iniciais: [0. 0.], Bias Inicial: 0.0)
Treino concluído. (Pesos Finais: [0.2 0.1], Bias Final: -0.20000000000000004)

Resultados:
Entrada | Desejado | Previsto | Correto?
------------------------------------------
[0 0]  |    0     |     0    |   Sim
[0 1]  |    0     |     0    |   Sim
[1 0]  |    0     |     0    |   Sim
[1 1]  |    1     |     1    |   Sim

Acurácia: 100.0%
Comentário: Sucesso! O Perceptron convergiu e aprendeu a função.

--- TESTANDO O CASO: OR ---
Treinando... (Pesos Iniciais: [0. 0.], Bias Inicial: 0.0)
Treino concluído. (Pesos Finais: [0.1 0.1], Bias Final: -0.1)

Resultados:
Entrada | Desejado | Previsto | Correto?
------------------------------------------
[0 0]  |    0     |     0    |   Sim
[0 1]  |    1     |     1    |   Sim
[1 0]  |    1     |     1    |   Sim
[1 1]  |    1     |     1    |   Sim

Acurácia: 100.0%
Comentário: Sucesso! O Perceptron convergiu e aprendeu a função.

--- TESTANDO O CASO: XOR ---

Resolvendo o caso XOR

In [ ]:
import numpy as np
# Vamos importar o MLPClassifier do Scikit-learn
from sklearn.neural_network import MLPClassifier
# Vamos usar o 'warnings' para suprimir avisos de convergência que podem aparecer
# em problemas simples, mas que não significam que o código falhou.
import warnings
from sklearn.exceptions import ConvergenceWarning

# ----------------------------------------------------------------
# PASSO 1: DEFINIR OS DADOS (igual ao anterior)
# ----------------------------------------------------------------

# Entradas (X) - Os 4 casos possíveis
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Saída desejada (y) para o XOR
y_xor = np.array([0, 1, 1, 0])

print(f"--- RESOLVENDO O CASO XOR COM MLP (Scikit-learn) ---")

# ----------------------------------------------------------------
# PASSO 2: CRIAR E TREINAR O MODELO MLP
# ----------------------------------------------------------------

# Estratégia de Inicialização (Definição da Arquitetura):
# Vamos criar um MLP com uma camada oculta.

# MLPClassifier(...)
#   hidden_layer_sizes=(4,):
#       Esta é a parte mais importante!
#       Define a arquitetura. (4,) significa UMA camada oculta com 4 neurônios.
#       Dois neurônios são o mínimo teórico para resolver o XOR, mas 4 é mais robusto.
#
#   activation='relu':
#       A função de ativação não-linear (Rectified Linear Unit).
#       É o que permite ao MLP aprender relações complexas.
#
#   solver='adam':
#       Um otimizador de aprendizado eficiente.
#
#   max_iter=5000:
#       Número máximo de épocas de treino. O XOR é complexo e precisa de mais treino.
#
#   random_state=1:
#       Define uma "semente" para a inicialização aleatória dos pesos.
#       Isso garante que nós dois teremos o MESMO resultado ao rodar o código.
#       O treino de redes neurais é sensível à inicialização dos pesos.

mlp = MLPClassifier(
    hidden_layer_sizes=(4,),
    activation='relu',
    solver='adam',
    max_iter=5000,
    random_state=1,
    learning_rate_init=0.01 # Uma taxa de aprendizado um pouco maior ajuda
)

# Suprimir o aviso de convergência
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=ConvergenceWarning, module="sklearn")

    # Treinar o modelo
    print("Treinando o MLP...")
    mlp.fit(X, y_xor)
    print("Treino concluído.")


# ----------------------------------------------------------------
# PASSO 3: FAZER AS PREVISÕES E MOSTRAR OS RESULTADOS
# ----------------------------------------------------------------

# Fazer as previsões com o modelo treinado
y_pred = mlp.predict(X)

# Mostrar os resultados
print("\nResultados do XOR com MLP:")
print("Entrada | Desejado | Previsto | Correto?")
print("------------------------------------------")

total_correct = 0
for i in range(len(X)):
    is_correct = "Sim" if y_xor[i] == y_pred[i] else "NÃO"
    if is_correct == "Sim":
        total_correct += 1
    print(f"{X[i]}  |    {y_xor[i]}     |     {y_pred[i]}    |   {is_correct}")

print(f"\nAcurácia: {total_correct / len(X) * 100}%")

if total_correct == len(X):
    print("Comentário: Sucesso! O MLP (com sua camada oculta) conseguiu aprender a função não-linear XOR.")
else:
    print("Comentário: Falha. O modelo não convergiu. Tente aumentar 'max_iter' ou alterar 'random_state'.")

# ----------------------------------------------------------------
# (Opcional) Ver os pesos que o modelo aprendeu
# ----------------------------------------------------------------
print("\n--- Pesos aprendidos pela rede ---")
print("Pesos da camada oculta (Input -> Oculta):")
print(mlp.coefs_[0])
print("\nBias da camada oculta:")
print(mlp.intercepts_[0])
print("\nPesos da camada de saída (Oculta -> Saída):")
print(mlp.coefs_[1])
print("\nBias da camada de saída:")
print(mlp.intercepts_[1])

--- RESOLVENDO O CASO XOR COM MLP (Scikit-learn) ---
Treinando o MLP...
Treino concluído.

Resultados do XOR com MLP:
Entrada | Desejado | Previsto | Correto?
------------------------------------------
[0 0]  |    0     |     0    |   Sim
[0 1]  |    1     |     1    |   Sim
[1 0]  |    1     |     1    |   Sim
[1 1]  |    0     |     0    |   Sim

Acurácia: 100.0%
Comentário: Sucesso! O MLP (com sua camada oculta) conseguiu aprender a função não-linear XOR.

--- Pesos aprendidos pela rede ---
Pesos da camada oculta (Input -> Oculta):
[[-2.98400588e-11  2.22919159e+00  1.36246054e-07 -2.46290385e+00]
 [ 7.74654930e-10 -2.22937221e+00 -5.88229378e-10  2.46227216e+00]]

Bias da camada oculta:
[-0.20646505  0.00038942 -0.16161097 -0.00095499]

Pesos da camada de saída (Oculta -> Saída):
[[-2.48482558e-10]
 [ 3.65749299e+00]
 [ 4.03442818e-07]
 [ 3.36408809e+00]]

Bias da camada de saída:
[-3.98301229]
